export const productTools = [
  {
    id: 1,
    src: "https://m.media-amazon.com/images/I/81leza6EFYL._AC_UL320_.jpg",
    name: "AmazonBasics 42-Piece Impact Screwdriver Bit Set - Phillips, Slotted and Torx",
    rating: 4,
    reviews: 2408,
    cost: 879,
    originalCost: 1500,
    discount: 41,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 2,
    src: "https://m.media-amazon.com/images/I/712pKc2fs5L._AC_UL320_.jpg",
    name: "DIP 46 in 1 Pcs Tool Kit & Screwdriver set and Socket Set Wrench Set Multi Purpose Combination Tool Case Precision Socket Set, Multicolour",
    rating: 5,
    reviews: 497,
    cost: 749,
    originalCost: 1299,
    discount: 42,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: true,
    isBestSeller: false,
  },
  {
    id: 3,
    src: "https://m.media-amazon.com/images/I/717NW1gwTZL._AC_UL320_.jpg",
    name: "BLACK+DECKER A7073 6V Battery Powered Screwdriver with 14 pc bits included (A7073-IN)",
    rating: 4,
    reviews: 9764,
    cost: 899,
    originalCost: 1575,
    discount: 43,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },

  {
    id: 4,
    src: "https://m.media-amazon.com/images/I/81xvKRhpMgL._AC_UL320_.jpg",
    name: "STANLEY 70-379E Matte Finish Double Open End Spanner Set 8-Piece Set Chrome",
    rating: 4,
    reviews: 8294,
    cost: 269,
    originalCost: 341,
    discount: 21,
    isDealOfTheDay: true,
    isPrime: false,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: true,
  },
  {
    id: 5,
    src: "https://m.media-amazon.com/images/I/81N4Cj+l8cL._AC_UL320_.jpg",
    name: "IBELL Electric Drill ED06-91, 400W, Copper Armature, 2800 RPM, Chuck 10 mm Forward/Reverse with Variable Speed Control",
    rating: 4,
    reviews: 1591,
    cost: 1271,
    originalCost: 2300,
    discount: 45,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: true,
  },
  {
    id: 6,
    src: "https://m.media-amazon.com/images/I/31lPh88YeGL._AC_UL320_.jpg",
    name: "STANLEY 70-482 8'' Sturdy Steel Combination Plier Double Color Sleeve (Yellow and Black)",
    rating: 4,
    reviews: 11142,
    cost: 240,
    originalCost: 312,
    discount: 23,
    isDealOfTheDay: true,
    isPrime: false,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 7,
    src: "https://m.media-amazon.com/images/I/61efxPuWijL._AC_UL320_.jpg",
    name: "MoreBlue Hao Yue Basic Digital Multimeter with Buzzer Square Wave Output Voltage Ampere Ohm Tester Probe DC AC LCD Overload Protection (Random Color)",
    rating: 3,
    reviews: 249,
    cost: 299,
    originalCost: 499,
    discount: 50,
    isDealOfTheDay: false,
    isPrime: false,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 8,
    src: "https://m.media-amazon.com/images/I/61T0LZkXchL._AC_UL320_.jpg",
    name: "STANLEY 51-152 Claw Hammer with Steel Shaft for masonry, wood work, fittings, DIY, mechanic work, and more, 220 grams, Limited Lifetime Warranty (Black and Chrome)",
    rating: 4,
    reviews: 8262,
    cost: 193,
    originalCost: 318,
    discount: 39,
    isDealOfTheDay: true,
    isPrime: false,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: true,
  },
  {
    id: 9,
    src: "https://m.media-amazon.com/images/I/41e9ZF288tL._AC_UL320_.jpg",
    name: "Boosty® 9 in 1 Micro Plier Tool Kit LED Flash Light Knife Blade Cutter Key Ring (9 in 1 Plier)",
    rating: 3,
    reviews: 53,
    cost: 329,
    originalCost: 599,
    discount: 45,
    isDealOfTheDay: false,
    isPrime: false,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 10,
    src: "https://m.media-amazon.com/images/I/61Cge6svJWL._AC_UL320_.jpg",
    name: "iBELL Inverter ARC Welding Machine (IGBT) 220A with Hot Start, Anti-Stick Functions, Arc Force Control - 2 Year Warranty",
    rating: 5,
    reviews: 5613,
    cost: 5276,
    originalCost: 5800,
    discount: 9,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: true,
    isBestSeller: false,
  },
  {
    id: 11,
    src: "https://m.media-amazon.com/images/I/71bM+WSv5YL._AC_UL320_.jpg",
    name: "Bosch GDC 121 Marble Cutter 5 Inch GDC 121",
    rating: 5,
    reviews: 2947,
    cost: 5490,
    originalCost: 5800,
    discount: "",
    isDealOfTheDay: false,
    isPrime: false,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: true,
  },
];

export const productStyles = [
  {
    id: 12,
    src: "https://m.media-amazon.com/images/I/71VIXbJQdxL._AC_UL320_.jpg",
    company: "Red Tape",
    name: "mens Jacket",
    rating: 4,
    reviews: 126,
    cost: 2339,
    originalCost: 7790,
    discount: 70,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 13,
    src: "https://m.media-amazon.com/images/I/41rA3M06R4L._AC_UL320_.jpg",
    company: "Campus Sutra",
    name: "Men's Camouflage/Military Hooded",
    rating: 5,
    reviews: 11,
    cost: 968,
    originalCost: 299,
    discount: 68,
    isDealOfTheDay: true,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 14,
    src: "https://m.media-amazon.com/images/I/41nvyksD5lL._AC_UL320_.jpg",
    company: "LEOTUDE",
    name: "Regular Fit Full Sleeve Cotton Blend Men's T-Shirt",
    rating: 4,
    reviews: 3837,
    cost: 424,
    originalCost: 1099,
    discount: "",
    isDealOfTheDay: false,
    isPrime: false,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: true,
  },
  {
    id: 15,
    src: "https://m.media-amazon.com/images/I/81H0ElKUXnL._AC_UL320_.jpg",
    company: "Woodland",
    name: "Men's Leather Sneakers",
    rating: 4,
    reviews: 1046,
    cost: 1752,
    originalCost: 3895,
    discount: 55,
    isDealOfTheDay: true,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 16,
    src: "https://m.media-amazon.com/images/I/814OCn0lIzL._AC_UL320_.jpg",
    company: "Sparx",
    name: "Men's Athletic and Outdoor Sandals",
    rating: 4,
    reviews: 13508,
    cost: 807,
    originalCost: 949,
    discount: 15,
    isDealOfTheDay: true,
    isPrime: false,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 17,
    src: "https://m.media-amazon.com/images/I/61373tSdppL._AC_UY218_.jpg",
    company: "",
    name: "uppercase Medium 23 Ltrs Tall Boy (14.6 inch) Laptop Backpack 2500EBP1 3x more water repellent sustainable bags with rain proof zippers for Men, Women, Boys and Girls",
    rating: 4,
    reviews: 84,
    cost: 1700,
    originalCost: 2300,
    discount: 26,
    isDealOfTheDay: false,
    isPrime: false,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 18,
    src: "https://m.media-amazon.com/images/I/81EASQlMkSS._AC_UY218_.jpg",
    company: "",
    name: "Bagneeds Men's Black Synthetic Leather Briefcase Best Laptop Messenger Bag Satchel for Men",
    rating: 4,
    reviews: 3108,
    cost: 664,
    originalCost: 1899,
    discount: 65,
    isDealOfTheDay: false,
    isPrime: false,
    isFreeDelivery: false,
    isAmazonsChoice: false,
    isBestSeller: true,
  },
  {
    id: 19,
    src: "https://m.media-amazon.com/images/I/610uMTA5DAL._AC_UY218_.jpg",
    company: "Killer",
    name: "Killer Louis 38L Large Laptop Backpack with 3 Compartments Black Polyester Trendy Waterproof Travel Backpack",
    rating: 4,
    reviews: 2074,
    cost: 1801,
    originalCost: 3199,
    discount: 44,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 20,
    src: "https://m.media-amazon.com/images/I/81eNprKPlZL._AC_UL320_.jpg",
    company: "TIMEWEAR",
    name: "Digital Men's Watch",
    rating: 4,
    reviews: 19231,
    cost: 699,
    originalCost: 3499,
    discount: 80,
    isDealOfTheDay: true,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: true,
  },
  {
    id: 21,
    src: "https://m.media-amazon.com/images/I/61epn29QG0L._AC_UL320_.jpg",
    company: "Noise",
    name: "Noise ColorFit Pulse Spo2 Smart Watch with 10 days battery life, 60+ Watch Faces, 1.4 (Full Touch HD Display Smartwatch, 24*7 Heart Rate Monitor Smart Band, Sleep Monitoring Smart Watches for Men and Women & IP68 Waterproof (Jet Black))",
    rating: 4,
    reviews: 63881,
    cost: 1899,
    originalCost: 4999,
    discount: 62,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 22,
    src: "https://m.media-amazon.com/images/I/71CEEzbDS-L._AC_UL320_.jpg",
    company: "Fastrack",
    name: "Black Magic Analog Black Dial Men's Watch",
    rating: 4,
    reviews: 3962,
    cost: 2149,
    originalCost: 2795,
    discount: 23,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
];

export const productDevices = [
  {
    id: 23,
    src: "https://m.media-amazon.com/images/I/61epn29QG0L._AC_UL320_.jpg",
    company: "Noise",
    name: "Noise ColorFit Pulse Spo2 Smart Watch with 10 days battery life, 60+ Watch Faces, 1.4 (Full Touch HD Display Smartwatch, 24*7 Heart Rate Monitor Smart Band, Sleep Monitoring Smart Watches for Men and Women & IP68 Waterproof (Jet Black))",
    rating: 4,
    reviews: 63881,
    cost: 1899,
    originalCost: 4999,
    discount: 62,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 24,
    src: "https://m.media-amazon.com/images/I/71X8NdnCsvL._AC_UL320_.jpg",
    company: "MI",
    name: "MI Smart Band 5- India's No. 1 Fitness Band, 1.1 ((2.8 cm) AMOLED Color Display, 2 Weeks Battery Life, Personal Activity Intelligence (PAI), 11 Sports Mode, Heart Rate, Women's Health Tracking (Black))",
    rating: 4,
    reviews: 71160,
    cost: 1999,
    originalCost: 2999,
    discount: 33,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: false,
    isAmazonsChoice: false,
    isBestSeller: true,
  },
  {
    id: 25,
    src: "https://m.media-amazon.com/images/I/71UBr5Gy4WL._AC_UY218_.jpg",
    company: "Maxima",
    name: "Maxima Max Pro X4 Smartwatch with SpO2,Upto 15 Day Battery life,Full-touch Ultra Bright 320*320 display of Upto 380 Nits,10+ Sports Mode,Continuous Heart Rate Monitoring&Unlimited Customized Watch Faces",
    rating: 4,
    reviews: 2932,
    cost: 2199,
    originalCost: 5999,
    discount: 63,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 26,
    src: "https://m.media-amazon.com/images/I/61Eb9vtdSML._AC_UY218_.jpg",
    company: "",
    name: "MI Pad 5 Snapdragon 860 2.5K Resolution, 120Hz Refresh Rate, Dci-P3, 27.81Cm Dolby Vision Display 6Gb Ram 128Gb Storage Quad Speaker Dolby Atmos Wi-Fi Tablets, Cosmic Gray",
    rating: 4,
    reviews: 1481,
    cost: 26999,
    originalCost: 37999,
    discount: 29,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: true,
    isBestSeller: false,
  },
  {
    id: 27,
    src: "https://m.media-amazon.com/images/I/61ODBAvzOXL._AC_UY218_.jpg",
    company: "",
    name: "Lenovo Tab M10 Fhd Plus (2Nd Gen) (10.3 Inch, 4Gb, 128 Gb, Wi-Fi + LTE, Volte Calling, Platinum Grey) with Earphone, Kids Mode with Parental Control, Posture Alert,Dolby Atmos Speakers",
    rating: 4,
    reviews: 8818,
    cost: 18999,
    originalCost: 35000,
    discount: 46,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 28,
    src: "https://m.media-amazon.com/images/I/41Htn4ZuioL._AC_UY218_.jpg",
    company: "",
    name: "Swipe Strike 8 Tablet (20 cm (8-inch), 3GB, 32GB, Wi-Fi + LTE, Voice Calling) (Glacier Blue)",
    rating: 3,
    reviews: 26,
    cost: 9999,
    originalCost: 16999,
    discount: 41,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 29,
    src: "https://m.media-amazon.com/images/I/51g12kaYslL._AC_UY218_.jpg",
    company: "",
    name: "Acer Extensa 15 Lightweight Laptop Intel Core i3 11th Gen Processor (4 GB RAM/256GB SSD/Windows 11 Home/Intel UHD Graphics /1.7Kg/Black) EX215-54 with 15.6 inc. (39.6 cms) Full HD Display",
    rating: 4,
    reviews: 281,
    cost: 29990,
    originalCost: 41999,
    discount: 29,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 30,
    src: "https://m.media-amazon.com/images/I/61BeBTB41DL._AC_UY218_.jpg",
    company: "",
    name: "(Renewed) Dell Latitude E5470 Intel Core i5 6th Gen.6200u Processor 14.1 Inches HD Screen Notebook Computer (8 GB Ram & 256 GB SSD, Windows 10 Pro, 1.71Kg)",
    rating: 3,
    reviews: 416,
    cost: 19484,
    originalCost: 69999,
    discount: 72,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: true,
  },
  {
    id: 31,
    src: "https://m.media-amazon.com/images/I/8150iUXkc5L._AC_UY218_.jpg",
    company: "",
    name: "Acer EK220Q 54.61 cm Full HD VA Panel Backlit LED Monitor with 250 Nits HDMI and VGA Ports Eye Care Features Like Bluelight Shield, Flickerless and Comfy View (1920 x 1080 Pixels, Black)",
    rating: 4,
    reviews: 1436,
    cost: 6299,
    originalCost: 13750,
    discount: 54,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: true,
    isBestSeller: false,
  },
  {
    id: 32,
    src: "https://m.media-amazon.com/images/I/61fy1xyLQRL._AC_UY218_.jpg",
    company: "",
    name: "LG - 19M38HB, 19 Inch (47cm) 1366 X 768 Pixels, Led HD Ready Monitor, TN Panel with VGA, Hdmi Ports (Black)",
    rating: 4,
    reviews: 2076,
    cost: 6700,
    originalCost: 9200,
    discount: 27,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 33,
    src: "https://m.media-amazon.com/images/I/61zMP-i0M7L._AC_UL320_.jpg",
    company: "",
    name: "Acer Qg241Y 23.8 Inch (60.45 cm) Backlit LED LCD Full Hd (1920 X 1080) VA Panel Gaming Monitor I 75Hz Refresh Rate I 1 Ms Vrb Response Time I 2 X Hdmi 1 X Vga I AMD Free Sync Technology I Black",
    rating: 4,
    reviews: 134,
    cost: 9299,
    originalCost: 11800,
    discount: 21,
    isDealOfTheDay: true,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
];

export const productHousehold = [
  {
    id: 34,
    src: "https://m.media-amazon.com/images/I/81FyYXoQF-L._AC_UY218_.jpg",
    company: "",
    name: "Samsung 192 L 2 Star Direct Cool Single Door Refrigerator (RR19A241BGS/NL, Grey Silver)",
    rating: 4,
    reviews: 5096,
    cost: 13190,
    originalCost: 14990,
    discount: 12,
    isDealOfTheDay: false,
    isPrime: false,
    isFreeDelivery: true,
    isAmazonsChoice: true,
    isBestSeller: false,
  },
  {
    id: 35,
    src: "https://m.media-amazon.com/images/I/717Kju6Tu2L._AC_UY218_.jpg",
    company: "",
    name: "Samsung 28 L Convection Microwave Oven (MC28A5013AK/TL, Black, Curd Anytime)",
    rating: 4,
    reviews: 3081,
    cost: 11590,
    originalCost: 15590,
    discount: 26,
    isDealOfTheDay: false,
    isPrime: false,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 36,
    src: "https://m.media-amazon.com/images/I/51M2WpKwb-L._AC_UY218_.jpg",
    company: "",
    name: "Borosil Chef Delite BCH20DBB21 300-Watt Chopper (Black)",
    rating: 5,
    reviews: 7566,
    cost: 1769,
    originalCost: 2340,
    discount: 24,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: true,
  },
  {
    id: 37,
    src: "https://m.media-amazon.com/images/I/71sD5XaN61L._AC_UY218_.jpg",
    company: "",
    name: "Sony Bravia 108 cm (43 inches) Full HD Smart LED Google TV KD-43W880K (Black) (2022 Model) | with Alexa Compatibility",
    rating: 5,
    reviews: 8,
    cost: 42740,
    originalCost: 64900,
    discount: 34,
    isDealOfTheDay: false,
    isPrime: false,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 38,
    src: "https://m.media-amazon.com/images/I/61YUFFFYRSL._AC_UY218_.jpg",
    company: "",
    name: "AmazonBasics 81 cm (32 inches) HD Ready Smart LED Fire TV AB32E10SS (Black)",
    rating: 4,
    reviews: 3611,
    cost: 12499,
    originalCost: 27000,
    discount: 54,
    isDealOfTheDay: false,
    isPrime: false,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: true,
  },
  {
    id: 39,
    src: "https://m.media-amazon.com/images/I/81+M1QrVNIL._AC_UY218_.jpg",
    company: "",
    name: "Prestige Iris 750 Watt Mixer Grinder with 3 Stainless Steel Jar + 1 Juicer Jar (White and Blue)",
    rating: 4,
    reviews: 41943,
    cost: 3099,
    originalCost: 6295,
    discount: 51,
    isDealOfTheDay: true,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 40,
    src: "https://m.media-amazon.com/images/I/51R6Ygn0WkL._AC_UL320_.jpg",
    company: "",
    name: "Casaliving Rolando Wood 4 Seater L Shape Sofa for Living Room with 2 Puffy - (Blue Grey) LHS",
    rating: 4,
    reviews: 108,
    cost: 16999,
    originalCost: 55999,
    discount: 70,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 41,
    src: "https://m.media-amazon.com/images/I/412CUyjDL1L._AC_UL320_.jpg",
    company: "",
    name: "Cane Crafts Medium Size Designer Bamboo Wooden Cane (Rattan, Bait) Chair for Lawn Chair, Arm Chair, Room Chair, Indoor Outdoor with Cushion",
    rating: 3,
    reviews: 30,
    cost: 2499,
    originalCost: 5990,
    discount: 58,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 42,
    src: "https://m.media-amazon.com/images/I/71ZmmLW97YL._AC_UL320_.jpg",
    company: "",
    name: "Cello Checkers Plastic PET Canister Set, 18 Pieces, Clear",
    rating: 4,
    reviews: 60160,
    cost: 549,
    originalCost: 1090,
    discount: 50,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: true,
  },
  {
    id: 43,
    src: "https://m.media-amazon.com/images/I/71In4MZCpQL._AC_UL320_.jpg",
    company: "",
    name: "Raafi Rafuf Wooden Intersecting Wall Shelves ( Set of 8 ) (Yellow & Black)",
    rating: 3,
    reviews: 70,
    cost: 1519,
    originalCost: 3699,
    discount: 59,
    isDealOfTheDay: true,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: false,
    isBestSeller: false,
  },
  {
    id: 44,
    src: "https://m.media-amazon.com/images/I/41Qduy7aggL._AC_UL320_.jpg",
    company: "",
    name: "Evaluemart Stainless Steel Sink Strainer Kitchen Drain Basin Basket Filter Stopper Drainer/Jali (4-inch/10 cm)",
    rating: 5,
    reviews: 2000,
    cost: 99,
    originalCost: 120,
    discount: 18,
    isDealOfTheDay: false,
    isPrime: true,
    isFreeDelivery: true,
    isAmazonsChoice: true,
    isBestSeller: false,
  },
];
